version: '3.9'

services:

  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      PGDATA: ${DATABASE_VOLUME}
    volumes:
      - database:/var/lib/postgresql/data
      #- ./tables.sql:/docker-entrypoint-initdb.d/tables.sql
    ports:
      - "5432:5432"
volumes:
  database: