server:
  port: 8080

spring:
  application:
    name: homework-16-spring-boot-serialization

logging:
  level:
    org:
      springframework: INFO
      hibernate: INFO
    com:
      example:
        demo: DEBUG
  file:
    name: logs/app.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger - %msg%n'
