server:
  port: 8080

spring:
  application:
    name: jdbc
  datasource:
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  docker:
    compose:
      file:  ./homework-14-spring-data-jdbc/docker-compose.yaml
